Project.create(name:"Dharmendra website")
Project.create(name:"Nirendra twitter")
Project.create(name:"Sharma website")
Project.create(name:"Ankita webite")
Person.create(name: "Anas Aijaz", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Back End Dev", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Danish Juneja", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Product Manager", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Anuran Saikia", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Android Dev", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Muthukumar", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Front End Dev", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Utkarsh Mahajan", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Server Manager", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Kunal Singh", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Social Media Marketing", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)
Person.create(name: "Shubhrank Mishra", image_url: "https://images.unsplash.com/flagged/photo-15706128...", work: "Graphic Designer", whatsapp: "7073312466", github: "https://github.com/anasaijaz", instagram: "https://www.instagram.com/mr.elliot.rose/", email: nil, registered: false)

